### ISSUE TITLE
How is it better than SCONS and meson?

### ISSUE THREAD

**Issue by KOLANICH** [xpybuild/xpybuild#11]

**Comment by mjj29** [comment]
Hi there. 

First of all I should say that I've never used scons or meson in anger, and hadn't heard of meson until you mentioned it, so I'm mostly going from their FAQs. At the time we started xpybuild we did evaluate scons - but I didn't personally - and it was a few years ago now, so things may have improved on that side.

SCONS

Xpybuild is probably most closely compared to scons. Both are written with their configuration files in Python allowing you very powerful ways to express your build configuration. Both of them have automatic parallelism, dependency checking and partial builds. They both have a similar make-like sources->targets declaratory model. There's also a similar globbing engine.

Unlike scons, xpybuild does treat directory targets like file targets in up to date checking, so you don't have to manually hack in a stamp file. We also include not just transitive dependencies like include files, but also all the flags etc that go into compiling a file in the implicit dependencies, which should ensure more correct partial builds. I said scons has a globbing engine, we have that, but a lot more powerful tools to refine filter and modify the things which are part of the build inputs in the declaration of targets.

Xpybuild has a property file, substitution variable and late-binding functor system which provides I think a better model for specifying paths, overriding them at run time, providing alternatives in different build modes or platforms. Fundamentally I think they have similar overlapping, but not the same feature sets. Scons seems a little better at automatically working out how to build on _this_ platform. Xpybuild seems better at having a build system which works well on _multiple_ platforms, when not everything about it can be automatically intuited.

There are also a lot of little features which are nice to have, like you can have xpybuild produce output compatible with Make, Visual Studio or Teamcity for integration with those tools, or tools which recognise those tools. There's also a curses animated progress bar. Xpybuild can automatically analyze the dependency tree and produce critical path outputs showing you where the time is spent, how well-utilized your mulitple threads are, etc, then provide priority hints to ensure that members of the critical path are queued early. Xpybuild has a principle of 'fail early' which means that many errors that could result in inconsistent or incorrect builds are explicit errors at build system parse time.

Lastly, our original reason for discarding scons was that we found at the time that it was quite slow for large projects. This may have changed since then, of course, but xpybuild was designed for a project with 1000s of targets, 10,000s of dependencies and 100,000s of lines of code across 4+ languages. It's used daily by a large enterprise software company and we put a lot of effort into making that fast and correct.

MESON

I'd guess that most of the advantages of scons over meson would also apply to xpybuild (for example their use of a DSL rather than python). From the FAQ, big things that I see as issues with meson include:

* no globbing/wildcard support
* The FAQ entry on how to use threads worries me about their automatic parallelism
* meson doesn't have user-defined functions, xpybuild is designed to be extensible, a feature that is used heavily in the aformentioned enterprise project.

They say this is all in aid of performance, but we have extremely quick no-opt and partial builds with xpybuild, so it would surprise me that they're really significantly better and they've sacrificed a lot of functionality.

**Comment by KOLANICH** [comment]
Thanks for the info.

**Comment by eli-schwartz** [comment]
> * no globbing/wildcard support

A definite tradeoff, but there are a couple reasons meson doesn't support this. One is indeed that it has performance penalties, not for no-op builds, but for *reconfiguring* and detecting newly-added files. In your comparison, you only mention no-op builds but not reconfiguring. :) I'd be curious how you handle the latter.

> * The FAQ entry on how to use threads worries me about their automatic parallelism

I'm curious what you think this has to do with parallelism? This is a dependency lookup for how to declare that a project requires to link to a threads library e.g. `gcc -pthread`, and in a manner similar to looking up the correct compiler flags to link to a system library by running, say, `pkg-config --cflags --libs libcurl`. (In fact, this uses the same frontend abstraction to look up either the threads library or a pkg-config library.)

It's the same thing CMake does with find_package() and scons does with, ugh, `env.ParseConfig('your custom shell command goes here')`.

(I cannot tell from reading your docs. Does xpybuild provide any built-in helpers for searching for system libraries? All I found was a `Link()` function that accepts `-l` names, but this won't scale for e.g. static linking the same way pkg-config handles dependency recursion, it cannot check version compatibility, it cannot be grouped in an interface together with includes... is the expected use of xpybuild, to run pkg-config using custom code and then split and pass the output as includes and libs to a link object?)

...

Build system parallelism as a measure of the number of build jobs that can be run at the same time? is an entirely different concept, and meson, too, includes automatic parallelism based on whatever rules it can infer about your inputs -> outputs, plus build file augmentations like the `depend_files` argument.

I suspect most build systems that aren't autotools can do that much correctly (autotools + make is famously prone to under-specified dependencies causing any attempt at parallelism to generally hit errors).

> * meson doesn't have user-defined functions, xpybuild is designed to be extensible, a feature that is used heavily in the aformentioned enterprise project.

That's a definite trade-off that not every build system is comfortable making :) and the advantage of not allowing extensibility is that if it turns out you don't need extensibility, your build descriptions will probably be simpler to understand. On the other hand, if you do need it, then not allowing it means the build system is completely useless for your purposes.

> Xpybuild has a principle of 'fail early' which means that many errors that could result in inconsistent or incorrect builds are explicit errors at build system parse time.

I would hope that this is a minimal bar any build system manages... although really it depends on what is deemed an "error" to begin with. :D

> We also include not just transitive dependencies like include files, but also all the flags etc that go into compiling a file in the implicit dependencies, which should ensure more correct partial builds.

Both cmake and meson support this as a side effect of being meta buildsystem *generators*, specifically, generating https://ninja-build.org/ descriptions.

autotools/make will notably lack this this... autotools may instead nuke the entire build on every configure update just in case, which is *painfully* slow.

**Comment by mjj29** [comment]
> > * no globbing/wildcard support
> 
> A definite tradeoff, but there are a couple reasons meson doesn't support this. One is indeed that it has performance penalties, not for no-op builds, but for _reconfiguring_ and detecting newly-added files. In your comparison, you only mention no-op builds but not reconfiguring. :) I'd be curious how you handle the latter.

We generate a file as part of the build containing all the build configuration including paths and use that to determine changes to the _configuration_, then also check to see whether any of the globbing would get more files. Turns out we can do this very quickly, so those noop build times include checking to see if any of the above changed.

> > * The FAQ entry on how to use threads worries me about their automatic parallelism
> 
> I'm curious what you think this has to do with parallelism? This is a dependency lookup for how to declare that a project requires to link to a threads library e.g. `gcc -pthread`, and in a manner similar to looking up the correct compiler flags to link to a system library by running, say, `pkg-config --cflags --libs libcurl`. (In fact, this uses the same frontend abstraction to look up either the threads library or a pkg-config library.)
> 
> It's the same thing CMake does with find_package() and scons does with, ugh, `env.ParseConfig('your custom shell command goes here')`.

Ah, OK, the FAQ entry confused me, use of threads here was coincidental and applies to 'any library that you're linking to'. I take it back.

> (I cannot tell from reading your docs. Does xpybuild provide any built-in helpers for searching for system libraries? All I found was a `Link()` function that accepts `-l` names, but this won't scale for e.g. static linking the same way pkg-config handles dependency recursion, it cannot check version compatibility, it cannot be grouped in an interface together with includes... is the expected use of xpybuild, to run pkg-config using custom code and then split and pass the output as includes and libs to a link object?)

I will definitely admit that this is one of the weaker points with xpybuild. We don't have as much automatic stuff in this regard than things like autotools or pkg-config. In our defense though: 1. noone should be doing static linking, so that's not an issue and 2. it turns out that it's actually not that harder to just list the -l names than the names of the libraries that you're linking to. I would like to improve this for sure, I've just not gotten around to it yet.

> ...
> 
> Build system parallelism as a measure of the number of build jobs that can be run at the same time? is an entirely different concept, and meson, too, includes automatic parallelism based on whatever rules it can infer about your inputs -> outputs, plus build file augmentations like the `depend_files` argument.

Right, I'm very happy with that, but I couldn't tell from the documentation. I did say I was just looking over the FAQ to try and work it out (-:

> I suspect most build systems that aren't autotools can do that much correctly (autotools + make is famously prone to under-specified dependencies causing any attempt at parallelism to generally hit errors).

And ant, visual studio, and many others, so I don't assume people do it right (-:
